language: node_js
node_js:
  - "12.16.1"

branches:
  only:
    - master

before_script:
  - npm install -g ionic cordova
  - ionic cordova platform add android

script:
  - ionic serve

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: www
